import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../sass/globals.scss";
import { ContextProvider } from "../contexts/app.context";
import Head from "next/head";

const lato = Lato({
  subsets: ['latin'],
  weight: ['300', '400', '700', '900']
})

export const metadata: Metadata = {
  title: "Project Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <Head>
        <link href="dist/hamburgers.css" rel="stylesheet"></link>
      </Head>
      
      <body className={lato.className}>
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
